### PR TITLE
Fixes bug where Astro  can't distinguish between two equal components…

### LINKED ISSUE #844: 🐛 BUG: two instances of the same React component taking different props on an .astro page both render with the same props
### What package manager are you using?

npm (on CodeSandbox)

### What operating system are you using?

ChromeOS

### Describe the Bug

Two separate instances of a component (each with different props) that displays a user's most recent tweet on the same Astro page end up rendering two individual tweet displays (as expected) however they are both of the same (second) user (unexpected). 

(NB: When the HTML is inspected, both components' astro-root uid are identical.)

### Steps to Reproduce

1. install react-twitter-widgets
2. Create a React component that accepts props.
eg:
`import React from "react";
import { Timeline } from "react-twitter-widgets";

const RecentTweet = ({ user }) => (
  <>
    <div className="tweet">
      <Timeline
        dataSource={{
          sourceType: "profile",
          screenName: user
        }}
        options={{
          width: "100",
          tweetLimit: "1"
        }}
      />
    </div>
  </>
);

export default RecentTweet;`

2. on an Astro page, import, render multiple instances of that component, using different props for each component
eg 
`
<RecentTweet user="user1" client:load />
<RecentTweet user="user2" client:load />
`
3. Error! Instead of the .astro page rendering two different Tweets, one from each user... two identical Tweets are rendered, both from user2's Twitter profile.

Screenshot 2021-07-24 18 15 20

Screenshot 2021-07-24 19 11 06

### Link to Minimal Reproducible Example (Optional)

_No response_

### PR DESCRIPTION
**Pull request by MatsDahlin**
## Changes

Includes a components props as distinguishing factor when generating hash for astroId, closes #844 

## Testing

Tested manually with example project. Would like help creating a unit test, but I can't get any Astro tests to run on my computer.

## Docs

Bug fix only, no change needed in docs.

### CODE REVIEW

File: packages/astro/src/internal/__astro_component.ts [hunk 1]
```diff
@@ -187,7 +187,8 @@ export function __astro_component(Component: any, metadata: AstroComponentMetada
     }
 
     // If we ARE hydrating this component, let's generate the hydration script
-    const astroId = hash.unique(html);
+    const stringifiedProps = JSON.stringify(props);
+    const astroId = hash.unique(html + stringifiedProps);
```
Comment (FredKSchott) [inline packages/astro/src/internal/__astro_component.ts:191]: what happens if two components with the same props? It sounds like we end up with two `astro-root` components with the same `uid` attribute. 

Curious if this is something that we should optimize for (just render all matching components with the same hydrate script) or be super explicit about (each component gets a completely unique id, not based on html).

Comment (matthewp) [reply packages/astro/src/internal/__astro_component.ts:191]: We should get rid of these inline scripts altogether imo and colocate everything in the head. A small inlined custom element would make these a lot easier.

But I think we should merge this fix in first because this seems like a bad bug to me.

Comment (MatsDahlin) [reply packages/astro/src/internal/__astro_component.ts:191]: > what happens if two components with the same props? It sounds like we end up with two `astro-root` components with the same `uid` attribute. 
> 
> 
> 
> Curious if this is something that we should optimize for (just render all matching components with the same hydrate script) or be super explicit about (each component gets a completely unique id, not based on html).

My opinion is that the way it currently works goes against established patterns of hydration, and it's not the expected behavior.

Using a modified version of the React counter component as an example:

```jsx

import React, { useState } from 'react';

export default function Counter({ initialValue, children }) {
  const [count, setCount] = useState(initialValue);
  const add = () => setCount((i) => i + 1);
  const subtract = () => setCount((i) => i - 1);

  return (
    <>
      <div className="counter">
        <button onClick={subtract}>-</button>
        <pre>{count}</pre>
        <button onClick={add}>+</button>
      </div>
      <div className="children">{children}</div>
    </>
  );
}

```

And then use two instances with different initial values in Astro:

```jsx
<Counter initialValue={0} />
<Counter initialValue={10} />
```

The above code would result in both Counter components being hydrated with the same initialValue.

I believe that using the components props as part of the hash generation gives us both the current optimization (identical components with identical props will get the same hydrate script) _and_ correctly hydrates components that differ only in what prop values get set from Astro.

**Comment by matthewp** [comment]
Going to merge, let's work to improve how we do hydration in another issue (maybe an RFC for an overhaul).
