### PR TITLE
Fix body scoping

### LINKED ISSUE #1074: 🐛 BUG: Unexpected behaviour when applying scoped styling to `html` and `body` tags in a `layout.astro` component
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I've got a `DefaultLayout.astro` with some scoped styles and this is what I'm setting:

```css
html,
body {
  height: 100%;
}
```

This results in the following CSS rendered in the browser:

```css
html,
body.astro-zvkshqHn {
  height: 100%;
}
```

The body doesn't get that class so the `height: 100%` is not applied.

### Steps to Reproduce

1. `npm start`
2. Set scoped classes in `DefaultLayout.astro`
3. Body class added to rendered CSS
4. Body class NOT added in rendered HTML

### Link to Minimal Reproducible Example (Optional)

_No response_

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #1074. In certain situations, our CSS scoping would encounter unexpected characters and scope classes unnecessarily (like `body`). This PR adds better css sanitization

## Testing

Test added.

## Docs

Bugfix; no docs needed.

### CODE REVIEW

File: packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts [hunk 1]
```diff
@@ -13,6 +13,11 @@ interface Selector {
 const CSS_SEPARATORS = new Set([' ', ',', '+', '>', '~']);
 const KEYFRAME_PERCENT = /\d+\.?\d*%/;
 
+/** minify selector CSS */
+function minifySelector(selector: string): string {
+  return selector.replace(/(\r?\n|\s)+/g, ' ').replace(/\s*(,|\+|>|~|\(|\))\s*/g, '$1');
```
Comment (drwpow) [inline packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts:18]: The change here is CSS sanitization. This removes any extraneous whitespace characters (including linebreaks) that aren’t essential to the CSS selector (keeping in mind that _some_ whitespace is essential as child selector, but other whitespace is non-essential such as `.foo   +   \n .bar` and can be removed).

The issue was whitespace not being handled properly, resulting in things like ` body` (rather than `body`) being a selector and incorrectly marked as needing scoping.

**Review by FredKSchott — APPROVED** [review]
