### PR TITLE
Fix for built scoped Vue styles

### LINKED ISSUE #1844: 🐛 BUG: Vue scoped styles applied globally during build step
### What version of `astro` are you using?

0.21.0-next.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

During dev step, scoped styles in Vue SFCs applied correctly (only to the elements inside the component). During build step, however, scoped styles are applied globally (i.e. to any matching element across the entire app).

In reproduction example, I added a scoped style to `Counter` `<button>`s. On stackblitz, it works as expected. It also works correctly, if you run `astro dev`. But if you run `astro build`, the scoped style will also apply to the button outside of the `Counter` component.

<details>
<summary>Here's how it looks if you build the example</summary>
Screenshot 2021-11-16 at 15 41 16
</details>

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qpj6s2

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Closes #1844
- Uses similar logic as the Vite CSS build plugin, which removes "pure css" code from imported JavaScript since we are including it as link tags.
- Also uses the Vue plugin's transform function so that it correctly scopes scoped CSS. We need to do this ourselves becuase our plugin is "pre" to avoid the Vite CSS build plugin from claiming CSS.

## Testing

Tests unskipped.

## Docs

N/A

### CODE REVIEW

File: packages/astro/src/vite-plugin-build-css/index.ts [hunk 1]
```diff
@@ -73,6 +74,11 @@ export function rollupPluginAstroBuildCSS(options: PluginOptions): VitePlugin {
         delete viteCSSPost.renderChunk;
         delete viteCSSPost.generateBundle;
       }
+
+      const viteVue = resolvedConfig.plugins.find((p) => p.name === 'vite:vue');
+      if(viteVue) {
+        vueTransform = viteVue.transform;
+      }
```
Comment (natemoo-re) [inline packages/astro/src/vite-plugin-build-css/index.ts:81]: This begs the question, what if another plugin handles CSS? Will we need to special-case all of them here?

If there's a safer way to call any possible transforms? Like passing `viteServer` into this plugin and calling `viteServer.pluginContainer.transform()`? I'd be in favor of exploring that, but you have more context here.

**Comment by FredKSchott** [comment]
1. is this issue impacting Svelte scoped styles as well?
2. is ` enforce: 'pre',` the root issue here? Curious if we could remove that to have this run after the Vue plugin instead of before.

**Review by natemoo-re — COMMENTED** [review]
Overall, looks great and glad this fixes it!

My one concern is that we're special casing this, but it doesn't feel like something that Astro should have to be concerned with. Is there any way we can leverage Vite to handle anything like this for us?

**Comment by matthewp** [comment]
> 1. is this issue impacting Svelte scoped styles as well?

No, there are Svelte scoped styles tests that are passing.

> 2. is enforce: 'pre', the root issue here? Curious if we could remove that to have this run after the Vue plugin instead of before.

Yes, it is, but no we can't remove it. We need to run before Vite's css-post plugin which is the equivalent of our CSS build plugin.

I did try that while working on this bug and it doesn't fix it and causes our CSS building not to work at all.

**Comment by matthewp** [comment]
> My one concern is that we're special casing this, but it doesn't feel like something that Astro should have to be concerned with. Is there any way we can leverage Vite to handle anything like this for us?

Not that I can think of. The root issue is that we don't want `vite:css-post` to run before us. I guess I could try outright *deleting* that hook.

File: packages/astro/src/vite-plugin-build-css/index.ts (hunk 1 above)
Comment (matthewp) [reply packages/astro/src/vite-plugin-build-css/index.ts:81]: That's worth a try.

**Comment by natemoo-re** [comment]
Thanks for the context @matthewp! Sounds like a tricky case. Totally happy to defer to you if you feel like this is the cleanest solution.

**Comment by matthewp** [comment]
I was able to remove all of our special casing. The issue comes down to us needing to run before the `vite:css-post` plugin. So the fix is to splice us right before that one. So now `vite:vue` runs before us, as well as `vite:css` and all of the other builtin plugins.

File: packages/astro/src/vite-plugin-build-css/index.ts [hunk 2]
```diff
@@ -56,28 +55,27 @@ export function rollupPluginAstroBuildCSS(options: PluginOptions): VitePlugin {
...
         delete viteCSSPost.renderChunk;
         delete viteCSSPost.generateBundle;
-      }
 
-      const viteVue = resolvedConfig.plugins.find((p) => p.name === 'vite:vue');
-      if(viteVue) {
-        vueTransform = viteVue.transform;
+        // Move our plugin to be right before this one.
+        const ourIndex = plugins.findIndex(p => p.name === PLUGIN_NAME);
+        const ourPlugin = plugins[ourIndex];
```
Comment (natemoo-re) [inline packages/astro/src/vite-plugin-build-css/index.ts:74]: `enforce: 'pre-pre-pre-FINAL'`

File: packages/astro/src/vite-plugin-build-css/index.ts [hunk 3]
```diff
@@ -56,28 +55,27 @@ export function rollupPluginAstroBuildCSS(options: PluginOptions): VitePlugin {
...
+
+        // Remove us from where we are now and place us right before the viteCSSPost plugin
+        plugins.splice(ourIndex, 1);
+        plugins.splice(viteCSSPostIndex - 1, 0, ourPlugin);
```
Comment (natemoo-re) [inline packages/astro/src/vite-plugin-build-css/index.ts:78]: Super clever! Nice solve. 👍🏻

**Review by natemoo-re — APPROVED** [review]
Dang, very clever solution. This is much cleaner!

File: packages/astro/src/vite-plugin-build-css/index.ts [hunk 4]
```diff
@@ -56,22 +55,27 @@ export function rollupPluginAstroBuildCSS(options: PluginOptions): VitePlugin {
...
 
-    enforce: 'pre',
-
     configResolved(resolvedConfig) {
-      viteTransform = getViteTransform(resolvedConfig);
 
-      const viteCSSPost = resolvedConfig.plugins.find((p) => p.name === 'vite:css-post');
-      if (viteCSSPost) {
+      const plugins = resolvedConfig.plugins as VitePlugin[];
+      const viteCSSPostIndex = resolvedConfig.plugins.findIndex((p) => p.name === 'vite:css-post');
```
Comment (FredKSchott) [inline packages/astro/src/vite-plugin-build-css/index.ts:64]: nit: a comment above all of this explaining why this is needed would be great. Also would help readers know that all we are doing is moving plugins around, and not calling or making changes to any of them.

**Review by FredKSchott — APPROVED** [review]
LGTM! 

Follow up question for later: I wonder if a plugin should be able to move itself like this, vs. having the Astro runtime be responsible for organizing plugin order. We own both in the same codebase so I guess it's not a huge difference either way, but just a thought about if we consider this a plugin reaching outside of itself.

**Comment by matthewp** [comment]
@FredKSchott I think it's a question that we can ask the Vite team: we want our plugin to run right before a specific other one, can we have an `enforce: { before: 'vite:css-post' }`
