### PR TITLE
Fix resolution of Astro.resolve in nested components

### LINKED ISSUE #1211: 🐛 BUG: Astro.resolve() doesn't work inside of components
### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

It appears that Astro components cannot use `Astro.resolve()` inside of components, since the resolver will always run relative to the page and not the component. Because components can show up on many pages, this renders the feature unusable in components in most projects.

Astro.resolve() does appear to work inside of pages.

@matthewp mind prioritizing a fix for this?

### Steps to Reproduce

1. `npm init astro` using template portfolio
2. Go to https://github.com/snowpackjs/astro/blob/main/examples/portfolio/src/components/MainHead.astro
3. Update the `link[href]` attribute to use `Astro.resolve()`, on a file relative to the component (you may need to create a CSS file inside of your src directory, somewhere like "src/styles/index.css".
4. Run `yarn build`
5. Notice that the build fails because on at least one page, the relative path will not work.

### Link to Minimal Reproducible Example (Optional)

_No response_

### PR DESCRIPTION
**Pull request by matthewp**
Fixes #1211
## Changes

Previously `Astro.resolve` was being passed down from the page to child components, causing it to always resolve from the page. Since that's not the behavior we want, I removed that code.

## Testing

Components were already tested, but nested components were not, which is why this bug was not caught in implementation.

## Docs

Bug fix only.

### CODE REVIEW

**Review by jasikpark — APPROVED** [review]
lgtm though i don't have a 100% understanding of it

**Comment by jasikpark** [comment]
How does the test work? Is it just testimg whether Astro.resolve will work in a child of a layout?

File: packages/astro/src/compiler/index.ts [hunk 1]
```diff
@@ -169,10 +169,6 @@ async function __render(props, ...children) {
       value: (props[__astroInternal] && props[__astroInternal].isPage) || false,
       enumerable: true
     },
-    resolve: {
```
Comment (FredKSchott) [inline packages/astro/src/compiler/index.ts:172]: ha! removing code ftw

**Review by FredKSchott — APPROVED** [review]

**Comment by matthewp** [comment]
@jasikpark 

> How does the test work? Is it just testimg whether Astro.resolve will work in a child of a layout?

It is making sure that the image has the correct (frontend) URL, which includes the nested component folder path.

The previous tests were resolving to a folder that is a sibling of pages and components so even though the code was wrong it resolved to the correct place. This new test makes sure it can resolve inside of the components folder.
