### PR TITLE
Prevent postcss from crashing when scoping class without a body

### LINKED ISSUE #340: empty CSS clause causes Astro to hang
In www, I added this to BlogPost.astro accidentally:

```
.author {
}
```

And Astro hung. I couldn't even kill it with Cmd+C.

### PR DESCRIPTION
**Pull request by matthewp**
Closes #340

## Changes

For some reason postcss will keep running the plugin over and over on a class without a body if we modify the `selector` (this triggers it as being "dirty"). It doesn't do this for selectors with a body. But the fix was easy enough, only scope a rule once.

## Testing

Added a test for this scenario.

## Docs

N/A

### CODE REVIEW

File: packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts [hunk 1]
```diff
@@ -96,10 +96,14 @@ export function scopeRule(selector: string, className: string) {
 
 /** PostCSS Scope plugin */
 export default function astroScopedStyles(options: AstroScopedOptions): Plugin {
+  const rulesScopedCache = new WeakSet();
```
Comment (drwpow) [inline packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts:99]: Nice!

Comment (drwpow) [reply packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts:99]: Actually, are we sure that this isn’t too aggressive? E.g. would this cache get hit if someone has a `.button` in separate files that should get different scopes?

**Review by drwpow — APPROVED** [review]
Awesome! Nice test
